import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./Component/Navbar";
import "./Layout.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Learning Next",
  description: "Generated by Learning Next",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div >
        <Navbar />
        {children}
      </div>
        </body>
    </html>
  );
}
